# Basic
title: imartinezl
email: inigomlap@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Description
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://imartinezl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  imartinezl
favicon: 'assets/images/favicon.ico'
google_analytics: G-DSNND8F3ZX
prev-next: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-scholar


css_dir: "assets/css" # defaults to "css"
color: blue
date_format: "%b %Y"
scholar:
  style: assets/scholar/apa3.csl
  bibliography_template: bib

# Collections
collections:
  projects:
    output: true
  tags:
    output: true
    permalink: /:collection/:path/


defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - yarn.lock
  - package-lock.json
  - README.md
  - LICENSE
  - postcss.config.js
  - tailwind.config.js
  - purgecss.config.js
  - bin
  - .gitignore
  - old_projects
  - generator